#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one-time creation of Freeze's release signing keys.
# ──────────────────────────────────────────────────────────────────────────
# Run from the repo root: bash scripts/setup-release-signing.sh
# Keys live outside the repo in ~/.freeze-signing. Re-running never replaces an
# existing key (a new key would break updates for every installed copy); it
# only re-uploads the secrets.

TOTAL_STAGES=5
KEYS=$(cygpath -m "$HOME/.freeze-signing" 2>/dev/null || echo "$HOME/.freeze-signing") # C:/… form works for bash and native tools
ENV_FILE="$KEYS/passwords.env"
P12_OPTS=(-keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -macalg sha1) # readable by macOS `security import` and Java

[[ -d .git && -d pc-companion ]] || { echo "Run this from the Freeze repo root."; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required (Git Bash ships it)."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "Log in first: gh auth login"; exit 1; }
mkdir -p "$KEYS"; chmod 700 "$KEYS"

# password KEY: reuse the saved password or generate one, and save it.
password() {
  local value; value=$(_existing "$1" || true)
  [[ -n "$value" ]] || value=$(openssl rand -hex 24)
  write_env "$1" "$value"
  printf -v "$1" '%s' "$value"
}

banner "Freeze release signing"

stage "Desktop updater key"
say "Installed desktop apps only accept updates signed with this key."
if [[ -f "$KEYS/updater.key" ]]; then
  note "Found $KEYS/updater.key, keeping it."
  password TAURI_PASSWORD
else
  password TAURI_PASSWORD
  (cd pc-companion && npx tauri signer generate --ci -w "$KEYS/updater.key" -p "$TAURI_PASSWORD") >/dev/null
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$KEYS/updater.key"
fi
node -e "const fs = require('fs'), p = 'pc-companion/src-tauri/tauri.conf.json', c = JSON.parse(fs.readFileSync(p, 'utf8'));
  c.plugins.updater.pubkey = fs.readFileSync(process.argv[1], 'utf8').trim(); fs.writeFileSync(p, JSON.stringify(c, null, 2) + '\n');" "$KEYS/updater.key.pub"
note "Public key written to pc-companion/src-tauri/tauri.conf.json (safe to commit)."
set_secret TAURI_SIGNING_PRIVATE_KEY "$(cat "$KEYS/updater.key")"
set_secret TAURI_SIGNING_PRIVATE_KEY_PASSWORD "$TAURI_PASSWORD"
pause

stage "Android release key"
say "Android installs an update only when it's signed with the same key as the installed app."
if [[ -f "$KEYS/android.p12" ]]; then
  note "Found $KEYS/android.p12, keeping it."
  password ANDROID_PASSWORD
else
  password ANDROID_PASSWORD
  MSYS_NO_PATHCONV=1 openssl req -x509 -newkey rsa:2048 -nodes -days 10000 -subj "/CN=Freeze" \
    -keyout "$KEYS/android.key.pem" -out "$KEYS/android.crt.pem" 2>/dev/null
  openssl pkcs12 -export -name freeze "${P12_OPTS[@]}" -inkey "$KEYS/android.key.pem" -in "$KEYS/android.crt.pem" \
    -out "$KEYS/android.p12" -passout "pass:$ANDROID_PASSWORD"
  rm "$KEYS/android.key.pem"
  printf '  %s✓ created%s %s (alias: freeze)\n' "$GREEN" "$RESET" "$KEYS/android.p12"
fi
set_secret ANDROID_KEYSTORE_BASE64 "$(openssl base64 -A -in "$KEYS/android.p12")"
set_secret ANDROID_KEYSTORE_PASSWORD "$ANDROID_PASSWORD"
pause

stage "macOS code-signing certificate"
say "Signing every build with this certificate keeps Freeze's Accessibility permission across updates."
if [[ -f "$KEYS/macos.p12" ]]; then
  note "Found $KEYS/macos.p12, keeping it."
  password MACOS_PASSWORD
else
  password MACOS_PASSWORD
  MSYS_NO_PATHCONV=1 openssl req -x509 -newkey rsa:2048 -nodes -days 7300 -subj "/CN=Freeze Self-Signed" \
    -addext "basicConstraints=critical,CA:false" -addext "keyUsage=critical,digitalSignature" \
    -addext "extendedKeyUsage=critical,codeSigning" \
    -keyout "$KEYS/macos.key.pem" -out "$KEYS/macos.crt.pem" 2>/dev/null
  openssl pkcs12 -export -name "Freeze Self-Signed" "${P12_OPTS[@]}" -inkey "$KEYS/macos.key.pem" -in "$KEYS/macos.crt.pem" \
    -out "$KEYS/macos.p12" -passout "pass:$MACOS_PASSWORD"
  rm "$KEYS/macos.key.pem"
  printf '  %s✓ created%s %s (identity: Freeze Self-Signed)\n' "$GREEN" "$RESET" "$KEYS/macos.p12"
fi
password KEYCHAIN_PASSWORD
set_secret APPLE_CERTIFICATE "$(openssl base64 -A -in "$KEYS/macos.p12")"
set_secret APPLE_CERTIFICATE_PASSWORD "$MACOS_PASSWORD"
set_secret KEYCHAIN_PASSWORD "$KEYCHAIN_PASSWORD"
pause

stage "Back up the keys"
warn "If these files are lost, installed copies can never update again."
say "Back up this whole folder somewhere that isn't this PC:"
say "  $KEYS"
step "Your password manager (attach the files, or the folder as a zip), or an encrypted USB drive."
step "Include passwords.env. It holds the three key passwords."
explorer.exe "$(cygpath -w "$KEYS" 2>/dev/null || echo "$KEYS")" >/dev/null 2>&1 || true
until confirm "Is the folder backed up?"; do note "The keys can't be recovered later. Back them up, then answer y."; done

stage "Scan the git history for leaked secrets"
say "Everything ever committed becomes public with the repo."
if ! command -v gitleaks >/dev/null 2>&1; then
  if confirm "gitleaks isn't installed. Install it with winget?"; then
    winget install --id Gitleaks.Gitleaks -e --accept-source-agreements --accept-package-agreements
    warn "Open a new terminal so gitleaks is on PATH, then re-run this wizard (keys are kept)."
    exit 0
  fi
  SKIPPED+=("History scan: install gitleaks, then run: gitleaks git -v .")
else
  if gitleaks git -v . ; then
    printf '  %s✓ no leaks found%s\n' "$GREEN" "$RESET"
  else
    warn "gitleaks found something. Paste the output to Claude before making the repo public."
    SKIPPED+=("Resolve the gitleaks findings above")
  fi
  pause
fi

finish
say "Next: commit pc-companion/src-tauri/tauri.conf.json (it now holds the updater public key)."
