// Run: node scripts/sync-web-fonts.ts
// Downloads the fonts the clock and PC stats widgets use from Google Fonts (once; they're SIL Open Font
// License) and writes:
//   pc-companion/src/fonts/*.woff2 and fonts.css  for the desktop app (bundled by Vite)
//   phone-app/src/web-fonts-source.ts            the same faces as data URIs, for the phone's widget page
// so neither app asks a server for a font while running. Only the Latin subset is kept: other scripts
// fall back to system fonts. scripts/check-web-fonts.ts verifies the generated files offline.
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';

const FAMILIES = 'family=Bricolage+Grotesque:opsz,wght@12..96,600;12..96,800&family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@500;600&family=Barlow+Condensed:wght@600';
// A modern Chrome user agent makes Google serve woff2 files.
const USER_AGENT = 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Mobile Safari/537.36';
const SUBSET = 'latin';

const css = await (await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { 'User-Agent': USER_AGENT } })).text();
type Face = { family: string; weights: number[]; url: string; range: string; stretch: boolean };
const faces = new Map<string, Face>();
for (const match of css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face\s*\{([^}]*)\}/g)) {
  if (match[1] !== SUBSET) continue;
  const body = match[2];
  const family = body.match(/font-family: '([^']+)'/)?.[1];
  const weight = Number(body.match(/font-weight: (\d+)/)?.[1]);
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const range = body.match(/unicode-range: ([^;]+);/)?.[1];
  if (!family || !weight || !url || !range) throw new Error(`Unexpected @font-face block: ${body}`);
  // Variable fonts come as one file listed once per weight: one face then covers the weight range.
  const key = `${family}|${url}`;
  const face = faces.get(key) ?? { family, weights: [], url, range, stretch: /font-stretch/.test(body) };
  face.weights.push(weight);
  faces.set(key, face);
}
if (faces.size === 0) throw new Error('No Latin faces found in the Google Fonts response');

const slug = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const dir = new URL('../pc-companion/src/fonts/', import.meta.url);
mkdirSync(dir, { recursive: true });
let desktopCss = '/* Generated by scripts/sync-web-fonts.ts: Latin faces of the fonts the clock and PC stats widgets use\n   (SIL Open Font License, see LICENSE.md). Edit the script, not this file. */\n';
let phoneCss = '';
const loads: string[] = [];
let totalBytes = 0;
for (const face of [...faces.values()].sort((a, b) => a.family.localeCompare(b.family) || a.weights[0] - b.weights[0])) {
  const bytes = Buffer.from(await (await fetch(face.url)).arrayBuffer());
  if (bytes.subarray(0, 4).toString('latin1') !== 'wOF2') throw new Error(`${face.url} is not a woff2 file`);
  const low = Math.min(...face.weights), high = Math.max(...face.weights);
  const weightText = low === high ? String(low) : `${low} ${high}`;
  const file = `${slug(face.family)}-${low === high ? low : `${low}-${high}`}-${SUBSET}.woff2`;
  writeFileSync(new URL(file, dir), bytes);
  totalBytes += bytes.length;
  const rule = (src: string) => `@font-face{font-family:'${face.family}';font-style:normal;font-weight:${weightText};${face.stretch ? 'font-stretch:100%;' : ''}font-display:swap;src:url(${src}) format('woff2');unicode-range:${face.range}}`;
  desktopCss += `${rule(`./${file}`)}\n`;
  phoneCss += rule(`data:font/woff2;base64,${bytes.toString('base64')}`);
  // A weight inside the range loads the whole face.
  loads.push(`${low} 16px "${face.family}"`);
}
writeFileSync(new URL('fonts.css', dir), desktopCss);
const digest = createHash('sha256').update(phoneCss).digest('hex').slice(0, 16);
writeFileSync(new URL('../phone-app/src/web-fonts-source.ts', import.meta.url),
  `// Generated by scripts/sync-web-fonts.ts from pc-companion/src/fonts/. Do not edit.\n// The fonts the clock and PC stats widgets use, embedded so the widget page never asks a server for them.\n// sha256:${digest}\nexport const WEB_FONTS_CSS = ${JSON.stringify(phoneCss)};\n// Font shorthands the page loads before drawing any widget, so text is measured with the right font.\nexport const WEB_FONT_LOADS = ${JSON.stringify(loads)};\n`);
console.log(`${faces.size} faces, ${(totalBytes / 1024).toFixed(0)} KB of woff2 written; phone module ${(phoneCss.length / 1024).toFixed(0)} KB`);
