// Run: node scripts/sync-pc-stats.ts
// Copies the shared PC stats widgets into the phone app as a string, for its WebView.
import { readFileSync, writeFileSync } from 'node:fs';

// Line endings depend on the checkout (core.autocrlf), so the phone copy always uses LF.
const source = readFileSync(new URL('../pc-companion/src/pc-stats/pc-stats.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
writeFileSync(
  new URL('../phone-app/src/pc-stats-source.ts', import.meta.url),
  `// Generated by scripts/sync-pc-stats.ts from pc-companion/src/pc-stats/pc-stats.js. Do not edit.\nexport const PC_STATS_SOURCE = ${JSON.stringify(source)};\n`,
);
console.log('phone-app/src/pc-stats-source.ts updated');
