// Run: node scripts/sync-clock-faces.ts
// Copies the shared clock faces into the phone app as a string, for its WebView.
import { readFileSync, writeFileSync } from 'node:fs';

const source = readFileSync(new URL('../pc-companion/src/clock-faces/clock-faces.js', import.meta.url), 'utf8');
writeFileSync(
  new URL('../phone-app/src/clock-faces-source.ts', import.meta.url),
  `// Generated by scripts/sync-clock-faces.ts from pc-companion/src/clock-faces/clock-faces.js. Do not edit.\nexport const CLOCK_FACES_SOURCE = ${JSON.stringify(source)};\n`,
);
console.log('phone-app/src/clock-faces-source.ts updated');
